### ISSUE TITLE
AI looping: "next action in the past"

### ISSUE THREAD

**Issue by Dibujaron** [Dibujaron/DistantHorizonIssues#19]
Exception in thread "mainThread" java.lang.IllegalStateException: next action is in the past? nat: 767, ct: 79635, route: 104
        at com.dibujaron.distanthorizon.database.impl.ExScriptDatabase$RelationalScriptReader.nextActionShouldFire(ExScriptDatabase.kt:135)
        at com.dibujaron.distanthorizon.ship.AIShip.computeNextState(AIShip.kt:14)
        at com.dibujaron.distanthorizon.ship.Ship.tick(Ship.kt:70)
        at com.dibujaron.distanthorizon.ship.ShipManager.tick(ShipManager.kt:37)
        at com.dibujaron.distanthorizon.DHServer.tick(DHServer.kt:113)
        at com.dibujaron.distanthorizon.DHServer.mainLoop(DHServer.kt:104)
        at com.dibujaron.distanthorizon.DHServer.access$mainLoop(DHServer.kt:29)
        at com.dibujaron.distanthorizon.DHServer$$special$$inlined$fixedRateTimer$1.run(Timer.kt:149)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
        at java.base/java.util.TimerThread.run(Timer.java:506)

**Comment by Dibujaron** [comment]
Exception in thread "mainThread" java.lang.IllegalStateException: next action is in the past? nat: 2289, ct: 85418, route: 3
        at com.dibujaron.distanthorizon.database.impl.ExScriptDatabase$RelationalScriptReader.nextActionShouldFire(ExScriptDatabase.kt:137)
        at com.dibujaron.distanthorizon.ship.AIShip.computeNextState(AIShip.kt:14)
        at com.dibujaron.distanthorizon.ship.Ship.tick(Ship.kt:70)
        at com.dibujaron.distanthorizon.ship.ShipManager.tick(ShipManager.kt:37)
        at com.dibujaron.distanthorizon.DHServer.tick(DHServer.kt:117)
        at com.dibujaron.distanthorizon.DHServer.mainLoop(DHServer.kt:108)
        at com.dibujaron.distanthorizon.DHServer.access$mainLoop(DHServer.kt:29)
        at com.dibujaron.distanthorizon.DHServer$$special$$inlined$fixedRateTimer$1.run(Timer.kt:149)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
        at java.base/java.util.TimerThread.run(Timer.java:506)
registered pending login for user Dibujaron0511, token is tok886484448
